[package]
name = "todo_dapp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.15.1"         
ic-cdk-macros = "0.9"
serde = "1.0"
serde_json = "1.0"
ic-cdk-timers = "0.9"
ic-stable-structures = "0.6.1"
